### ISSUE TITLE
Function to set a custom user-agent string

### ISSUE THREAD

**Issue by dapgo** [jonathan-reisdorf/bb10-minimalistic-browser#8]
It would be very useful to be able to set how the browser is identified. 
For certain pages and skilled users it  is a very useful feature that enables to force some tricky webpages  to work on your webbrowser.

**Comment by jonathan-reisdorf** [comment]
Yes, that would be easy to add for the use with crosswalk, since I have to specify the user agent string on initialization anyway. I might have to slightly adapt the feature once I switch to using pure chromium (from version 2.0.0 on), but I can add this feature before the switch since implementing pure chromium takes more time than anticipated.

**Comment by jonathan-reisdorf** [comment]
fixed by https://github.com/jonathan-reisdorf/bb10-minimalistic-browser/pull/10
